on:
  push:
name: 测试构建 com.binance.Binance
jobs:
  test-build-binance:
    name: "test-build-binance"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
      - name: 构建 Flatpak
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: com.binance.Binance.flatpak
          manifest-path: com.binance.Binance/com.binance.Binance.yml
