on:
  push:
name: 测试构建 com.netease.CloudMusic
jobs:
  test-build-cloudmusic:
    name: "test-build-cloudmusic"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: 构建 Flatpak
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: com.netease.CloudMusic.flatpak
          manifest-path: com.netease.CloudMusic/com.netease.CloudMusic.yml
