name: 构建 design.js.Design
on:
  push:
    paths:
      - design.js.Design/*
      - .github/workflows/design.yml
jobs:
  test-build-design:
    runs-on: ubuntu-latest
    name: test-build-design
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: 构建 Flatpak
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: design.js.Design.flatpak
          manifest-path: design.js.Design/design.js.Design.yml
