name: 构建 com.alibabainc.DingTalk
on:
  push:
    paths:
      - com.alibabainc.DingTalk/*
      - .github/workflows/dingtalk.yml
jobs:
  test-build-dingtalk:
    runs-on: ubuntu-latest
    name: test-build-dingtalk
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: 构建 Flatpak
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: com.alibabainc.DingTalk.flatpak
          manifest-path: com.alibabainc.DingTalk/com.alibabainc.DingTalk.yml
